import { useRef, useState } from 'react';
import { Download, Plus, Save, Trash2, Upload } from 'lucide-react';

export default function Settings({ settings, categories, onSaveSettings, onAddCategory, onDeleteCategory, onBackup, onRestore }) {
  const [balance,setBalance]=useState(settings.initialBalance); const [name,setName]=useState(''); const [sub,setSub]=useState(''); const [color,setColor]=useState('#172A46'); const fileRef=useRef();
  return <div className="page"><div className="page-title"><p className="eyebrow">Personalización</p><h1>Configuración</h1></div>
  <div className="settings-grid"><section className="panel"><h2>Balance inicial</h2><p className="muted">Se configura una sola vez y puedes editarlo cuando sea necesario.</p><label>Valor inicial<input type="number" value={balance} onChange={e=>setBalance(e.target.value)}/></label><button className="primary-btn" onClick={()=>onSaveSettings({...settings,initialBalance:Number(balance)})}><Save size={18}/>Guardar balance</button></section>
  <section className="panel"><h2>Nueva categoría</h2><div className="form-grid"><label>Nombre<input value={name} onChange={e=>setName(e.target.value)} placeholder="Ej. APC"/></label><label>Color<input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label className="full">Subcategorías iniciales<input value={sub} onChange={e=>setSub(e.target.value)} placeholder="Separadas por coma: Cancha, Pelotas"/></label></div><button className="primary-btn" onClick={()=>{if(!name.trim())return;onAddCategory({name:name.trim(),color,subcategories:sub.split(',').map(x=>x.trim()).filter(Boolean)});setName('');setSub('')}}><Plus size={18}/>Crear categoría</button></section>
  <section className="panel full-panel"><h2>Categorías actuales</h2><div className="category-grid">{categories.map(c=><article className="category-card" key={c.id}><div className="category-color" style={{background:c.color}}/><div><h3>{c.name}</h3><p>{c.subcategories?.join(' · ')||'Sin subcategorías'}</p></div><button onClick={()=>onDeleteCategory(c.id)}><Trash2 size={17}/></button></article>)}</div></section>
  <section className="panel full-panel"><h2>Respaldo de datos</h2><p className="muted">Descarga un respaldo JSON o restaura uno anterior.</p><div className="form-actions"><button className="primary-btn" onClick={onBackup}><Download size={18}/>Descargar respaldo</button><button className="ghost-btn" onClick={()=>fileRef.current?.click()}><Upload size={18}/>Restaurar respaldo</button><input ref={fileRef} hidden type="file" accept="application/json" onChange={e=>onRestore(e.target.files?.[0])}/></div></section></div></div>
}
